version: 1.0
frontend:
  phases:
    preBuild:
      commands:
        - npm install --production
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/* # Acelera las construcciones futuras